name: gal_example
description: Demonstrates how to use the gal plugin.
version: 2.2.0
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: 5.4.0
  gal: ^2.2.0
  gal_linux:
    path: ../

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
     - assets/