name: gal_linux
description: "Unofficial Linux implementation of the gal_linux plugin."
version: 0.1.2
homepage: https://github.com/EchoEllet/gal-linux/
repository: https://github.com/EchoEllet/gal-linux/
issue_tracker: https://github.com/EchoEllet/gal-linux/issues/
documentation: https://github.com/EchoEllet/gal-linux/

platforms:
  linux:

topics:
 - gallery
 - video
 - image
 - photos
 - util

environment:
  sdk: '>=3.2.2 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  gal: ^2.3.0
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    implements: gal
    platforms:
      linux:
        dartPluginClass: GalPluginLinux